# Generated by Django 3.0.5 on 2021-08-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_auto_20210807_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='current_balance',
        ),
    ]
