# Generated by Django 3.0.5 on 2021-08-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0003_remove_customer_current_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='current_balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
