# Generated by Django 3.0.5 on 2021-08-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0004_customer_current_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=100)),
                ('sender_name', models.CharField(max_length=100)),
                ('receiver_id', models.CharField(max_length=100)),
                ('receiver_name', models.CharField(max_length=100)),
                ('Amount', models.CharField(max_length=10)),
            ],
        ),
    ]
